### ISSUE TITLE
Player slows down with heavy MIDI Event load

### ISSUE THREAD

**Issue by ctrninja** [grimmdude/MidiPlayerJS#3]
Your MIDI Player seems to slow down when it is fed with several MIDI events at a time, making more complex MIDI arrangements impossible to play on the player, such as Circus Galop, or any kind of "Black MIDI".  To add on to that, only the MIDI Track that exceeds the amount of simultaneous MIDI Events it can handle slows down individually, causing the rest of the MIDI Tracks to be temporarily out of sync.  Hopefully this is an easy fix.

**Comment by grimmdude** [comment]
Hi There,

Thanks for your message.  I'm aware of some timing issues which are probably related to the issues you're seeing (#1 is also affected by this).  I will work on this shortly and hopefully reply back with the solution.  

Would you be able to provide links to the MIDI files in question by chance?

-Garrett

**Comment by grimmdude** [comment]
Also, I believe there will always be a bit of a performance hit when playing back highly complex MIDI files through the browser because of the inherit inefficiencies of the environment.  There may be things we can do in the code to account for this though, like turn down the playback "resolution".

-Garrett

**Comment by ray890** [comment]
Greetings, I'm someone who assisted the OP in formulating the original post.  I for one am familiar with the performance flaws derived from any use of web environments, that being said there is more of a throughput hit than I would expect from such a tool and certainly can improve within the web platform.

The existence and playback of a MIDI genre known as "Black MIDI" is what has led us to find this problem so quick.  I'd usually expect MIDI sequences like what I've linked to at least have reasonable playability on a web application such as yours, these samples are at the very low end of the complexity spectrum of Black MIDIs.

https://drive.google.com/open?id=0ByIDTUMUvYUWSllmZ1NzWms1ckk

-Ray

**Comment by grimmdude** [comment]
Hi @ray890,

I looked into this, and I don't believe the player itself is slowing down under the heavy throughput of these songs, however the browser is having trouble keeping up with triggering the sounds (which are audio files) and driving up CPU.  I'm going to see if using an oscillator native to the browser, as opposed to audio files, helps at all.

> I'd usually expect MIDI sequences like what I've linked to at least have reasonable playability on a web application such as yours, these samples are at the very low end of the complexity spectrum of Black MIDIs.

Is there a link you can send me to one that plays these files well?  I'd like to see how they're handling this situation if possible.  Thanks,

-Garrett

**Comment by qwirk** [comment]
http://www.grandgent.com/tom/projects/tmidi/

**Comment by grimmdude** [comment]
Hi @qwirk,

Thanks, it looks like that's a Windows based application written in C++ though.  Do you know of any web based MIDI players that can efficiently play these songs?

-Garrett

**Comment by qwirk** [comment]
http://www.midijs.net/

**Comment by grimmdude** [comment]
Hi @OptimumPrimus ,

Sorry for the late reply.  Were you able to use the MIDI player you posted above to play your black MIDI songs?

-Garrett

**Comment by xKyup** [comment]
Yes, it played flawlessly but it doesn't work in node.js

**Comment by grimmdude** [comment]
I'm going to close this out since the player being referred to is just an example of what MidiPlayerJS is capable of using Soundfont Player library (https://github.com/danigb/soundfont-player) to generate the sounds.  There may be a way to make the player demo more efficient in heavy event load using native Web Audio API sounds, but it's not really related to the core function of MidiPlayerJS.

The name "MidiPlayerJS" may be a bit misleading since this library is more of an engine which emits MIDI events in JSON format and it seems to handle heavy event loads fine on it's own detached from any audio.  I may work on incorporating Web Audio API sounds into the player when I have some time, but feel free give it a shot yourself.

-Garrett
